apiVersion: v1
kind: Secret
metadata:
  name: email-password
type: Opaque
data:
  password: ZGNtYXljZnlqcmxnaHN3eQ==
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
     smtp_smarthost: smtp.gmail.com:465
     smtp_from: alertmanager@hire.com
     smtp_auth_username: awspractice1999@gmail.com
     smtp_auth_password: "$email-password"
     smtp_require_tls: false
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 1m
      receiver: mail

    receivers:
     - name: 'mail'
       email_configs:
       - to: awspractice1999@gmail.com
         smarthost: smtp.gmail.com:465
         auth_username: awspractice1999@gmail.com
         auth_password: "$email-password"

         send_resolved: true


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
  labels:
    name: alertmanager
    
  name: alertmanager
  namespace: monitoring
spec:
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: alertmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      name: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        image: prom/alertmanager:v0.20.0
        name: alertmanager
        env:
          - name: email-password
            valueFrom:
              secretKeyRef:
                name: email-password
                key: password
        ports:
        - containerPort: 9093
          name: alertmanager
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: config-volume
        - mountPath: /alertmanager
          name: alertmanager
      volumes:
      - configMap:
          name: alertmanager
        name: config-volume
      - emptyDir: {}
        name: alertmanager
